framework:
    secret: '%env(APP_SECRET)%'
    default_locale: fr
    #csrf_protection: null
    #http_method_override: true
    #trusted_hosts: null
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        name: 'travelbook'
    #esi: ~
    #fragments: ~
    assets: ~
    php_errors:
        log: true
