security:
    encoders:
        App\Entity\User: bcrypt

    providers:
        users:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        unsecured:
            pattern: ^/(login|registration|password-lost|active/.*)?$
            anonymous: true

        app:
            provider: users
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login_check
                success_handler: App\Handler\AuthenticationSuccessHandler
            logout:
                path: app_logout
                target: app_login
