sudo: required

services:
    - docker

before_script:
    - cp .env.dist .env
    - docker run -d --name docker-hostmanager --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /etc/hosts:/hosts iamluc/docker-hostmanager
    - docker network create travelbook
    - docker-compose -p travelbook -f docker-compose.yml up -d --remove-orphans
    - docker run --rm --net=travelbook -e TIMEOUT=30 -e TARGETS=php:9000 ddn0/wait 2> /dev/null
    - docker run --rm --net=travelbook -e TIMEOUT=30 -e TARGETS=db:5432 ddn0/wait 2> /dev/null
    - docker-compose -p travelbook -f docker-compose.yml exec db /usr/local/src/init.sh
    - docker-compose -p travelbook -f docker-compose.yml run --rm php bin/install

script:
    - docker-compose -p travelbook -f docker-compose.yml run --rm php bin/console security:check
    - docker-compose -p travelbook -f docker-compose.yml run --rm php vendor/bin/php-cs-fixer fix -v --dry-run --diff --config=.php_cs.dist
    - docker-compose -p travelbook -f docker-compose.yml run --rm php bin/console lint:yaml config/
    - docker-compose -p travelbook -f docker-compose.yml run --rm php bin/console lint:twig templates/
    - docker-compose -p travelbook -f docker-compose.yml exec -T php vendor/bin/phpunit

notifications:
    email:
        - dewez.nicolas@gmail.com
