version: '2'

networks:
    travelbook:
        external: true

services:
    app:
        build: docker/app
        working_dir: /var/www/app
        environment:
            XDEBUG_ENABLED: 0
        env_file:
            - .env
        networks:
            travelbook:
                aliases:
                    - app
        volumes:
            - .:/var/www/app
            - ~/.composer:/var/www/.composer
        depends_on:
            - db

    web:
        image: nginx:1-alpine
        networks:
            travelbook:
                aliases:
                    - travelbook
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app:ro
        expose:
            - 80
        depends_on:
            - app

    db:
        image: postgres:latest
        ports:
            - "5433:5432"
        networks:
            travelbook:
                aliases:
                    - db
        volumes:
            - ./docker/db:/usr/local/src

    rabbitmq:
        image: rabbitmq:3-management
        ports:
           - "15672:15672"
           - "5672:5672"
        networks:
           travelbook:
               aliases:
                   - rabbitmq

    mailer:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
           travelbook:
               aliases:
                   - mailer
