version: '2'

networks:
    # local network
    travelbook:
        external: true

    # Internal & Stub
    default:

services:
    php:
        build: docker/php
        working_dir: /var/www/app
        env_file:
            - .env
        networks:
            travelbook:
                aliases:
                    - php
            default:
                aliases:
                    - php.travelbook
        volumes:
            - .:/var/www/app
            - ~/.composer:/var/www/.composer
        depends_on:
            - db

    web:
        image: nginx:1-alpine
        networks:
            travelbook:
                aliases:
                    - travelbook
            default:
                aliases:
                    - web.travelbook
        volumes:
            - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/app:ro
        expose:
            - 80
        depends_on:
            - php

    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        networks:
            travelbook:
                aliases:
                    - db
            default:
                aliases:
                    - db.travelbook
        volumes:
            - ./docker/db:/usr/local/src
