app_home:
    title: 'breadcrumb.app_home'

app_registration:
    title: 'breadcrumb.app_registration'
    parent: 'app_home'

app_password_lost:
    title: 'breadcrumb.app_password_lost'
    parent: 'app_home'

app_login:
    title: 'breadcrumb.app_login'
    parent: 'app_home'

app_change_password:
    title: 'breadcrumb.app_change_password'

app_my_account:
    title: 'breadcrumb.app_my_account'

app_admin_users_list:
    title: 'breadcrumb.app_admin_users_list'

app_admin_users_create:
    title: 'breadcrumb.app_admin_users_create'
    parent: 'app_admin_users_list'

app_admin_users_edit:
    title: 'breadcrumb.app_admin_users_edit'
    parent: 'app_admin_users_list'

app_admin_places_list:
    title: 'breadcrumb.app_admin_places_list'

app_admin_places_create:
    title: 'breadcrumb.app_admin_places_create'
    parent: 'app_admin_places_list'

app_admin_places_edit:
    title: 'breadcrumb.app_admin_places_edit'
    parent: 'app_admin_places_list'

app_validation_pictures_list:
    title: 'breadcrumb.app_validation_pictures_list'

app_validation_pictures_invalidation:
    title: 'breadcrumb.app_validation_pictures_invalidation'
    parent: 'app_validation_pictures_list'

app_validation_pictures_list_processed:
    title: 'breadcrumb.app_validation_pictures_list_processed'

app_validation_pictures_revalidation:
    title: 'breadcrumb.app_validation_pictures_revalidation'
    parent: 'app_validation_pictures_list_processed'

app_travels:
    title: 'breadcrumb.app_travels'

app_travels_create_step1:
    title: 'breadcrumb.app_travels_create_step1'
