controllers:
    resource: '../src/Controller/'
    type: 'annotation'

app_login_check:
    path: '/login-check'
    methods: ['POST']

app_logout:
    path: '/logout'
    methods: ['GET']

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
